# -*- coding: utf-8 -*-


""" Constants taken from Boostrap 4 """


""" Standard colors """

COLOR_BLACK = '#212529'
COLOR_WHITE = '#fff'


""" Colors """

COLOR_PRIMARY = '#007bff'
COLOR_PRIMARY_BORDER = COLOR_PRIMARY
COLOR_PRIMARY_HOVER = '#0069d9'
COLOR_PRIMARY_HOVER_BORDER = '#0062cc'
COLOR_PRIMARY_TEXT = COLOR_WHITE

COLOR_SECONDARY = '#6c757d'
COLOR_SECONDARY_BORDER = COLOR_SECONDARY
COLOR_SECONDARY_HOVER = '#5a6268'
COLOR_SECONDARY_HOVER_BORDER = '#545b62'
COLOR_SECONDARY_TEXT = COLOR_WHITE

COLOR_SUCCESS = '#28a745;'
COLOR_SUCCESS_BORDER = COLOR_SUCCESS
COLOR_SUCCESS_HOVER = '#218838'
COLOR_SUCCESS_HOVER_BORDER = '#1e7e34'
COLOR_SUCCESS_TEXT = COLOR_WHITE

COLOR_INFO = '#17a2b8'
COLOR_INFO_BORDER = COLOR_INFO
COLOR_INFO_HOVER = '#138496'
COLOR_INFO_HOVER_BORDER = '#117a8b'
COLOR_INFO_TEXT = COLOR_WHITE

COLOR_WARNING = '#ffc107'
COLOR_WARNING_BORDER = COLOR_WARNING
COLOR_WARNING_HOVER = '#e0a800'
COLOR_WARNING_HOVER_BORDER = '#d39e00'
COLOR_WARNING_TEXT = COLOR_BLACK

COLOR_DANGER = '#dc3545'
COLOR_DANGER_BORDER = COLOR_DANGER
COLOR_DANGER_HOVER = '#c82333'
COLOR_DANGER_HOVER_BORDER = '#bd2130'
COLOR_DANGER_TEXT = COLOR_WHITE

COLOR_DARK = '#343a40;'
COLOR_DARK_BORDER = COLOR_DARK
COLOR_DARK_HOVER = '#23272b'
COLOR_DARK_HOVER_BORDER = '#1d2124'
COLOR_DARK_TEXT = COLOR_WHITE

COLOR_LIGHT = '#f8f9fa;'
COLOR_LIGHT_BORDER = COLOR_LIGHT
COLOR_LIGHT_HOVER = '#138496'
COLOR_LIGHT_HOVER_BORDER = '#117a8b'
COLOR_LIGHT_TEXT = COLOR_BLACK
